version: "3"

services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "./migrations:/docker-entrypoint-initdb.d"
    ports:
      - "5430:5432"