version: "3"

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=main
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./src/db_init:/docker-entrypoint-initdb.d"
