import os

TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
CHAT_ID_NEW = os.getenv("TELEGRAM_CHANNEL_ID")
CHAT_ID_POPULAR = os.getenv("TELEGRAM_POPULAR_CHANNEL_ID")
COMMENTS_GROUP_ID = os.getenv("TELEGRAM_COMMENTS_GROUP_ID")
COMMENTS_GROUP_TAG = os.getenv("TELEGRAM_COMMENTS_GROUP_TAG")
